### ISSUE TITLE
Questions regarding this project

### ISSUE THREAD

**Issue by Joe23232** [quintinfsmith/wrecked#1]
Hi, I recently discovered this crate (through the Rust forums) and I wanted to ask some questions:
1. Is the API going to change with each update as I believe this crate is not stable?
2. Since it is under GPLv2 license, does this mean that any applications that I make with this crate, do I have to legally disclose my source code?
3. Am I able to make something like this with your crate?

![image](https://user-images.githubusercontent.com/34926497/104110823-9303cc00-532f-11eb-9a0d-1036eda1414f.png)
![demo](https://user-images.githubusercontent.com/34926497/104110852-ccd4d280-532f-11eb-8039-80764824a9d3.gif)

**Comment by quintinfsmith** [comment]
1. The API will be unstable until v1.0.0. That's a couple months off.
2. To the best of my understanding of the GPLv2, you only have to disclose the source of derivatives or modifications.  So no.
3. Absolutely, but it's designed without any prefabricated templates so you'd need to build something that, for example, plots graphs using this library.

**Comment by Joe23232** [comment]
@quintinfsmith Hi mate thanks for your response.

> 2. To the best of my understanding of the GPLv2, you only have to disclose the source of derivatives or modifications. So no.

In regards to question 2, somebody over on the Rust forum has said the exact opposite, he claims that you _do_ have to disclose your source code for the crate you use.
[https://users.rust-lang.org/t/is-there-an-easier-terminal-gui-crate-out-there/53913/4?u=joe232](https://users.rust-lang.org/t/is-there-an-easier-terminal-gui-crate-out-there/53913/4?u=joe232)

I would love to use your project but honestly if I want keep my projects closed source I legally can't due to this license. I don't think this license is particularly desirable, particularly for other developers, unless if I and the mod on the post is mistaken?

**Comment by quintinfsmith** [comment]
Fair play, looks like I wanted to use the LGPL anyway, so I've switched to that license. You can use it unmodified in your project, still need to include a link to the original wrecked source though.

**Comment by Joe23232** [comment]
@quintinfsmith Thanks mate, thats awesome, looking forward to using your crate :+1: 

> You can use it unmodified in your project, still need to include a link to the original wrecked source though.

So I can legally make my source code to the project closed source, right?

By the way is there some man pages or something for your crate?

**Comment by quintinfsmith** [comment]
Yes you can. Though I'd urge you to consider that in using this code, you would be benefiting from open source (and free) material.
Documentation can be found at https://docs.rs/wrecked through https://crates.io/crates/wrecked.

**Comment by Joe23232** [comment]
> Yes you can. Though I'd urge you to consider that in using this code, you would be benefiting from open source (and free) material.

Most of the time I would be open sourcing my code but in the future there could be a time where I would want to close source my code (for whatever reason it can be) so I wanted to know if I am using the right crate to allow me to close source it :+1:

> Documentation can be found at https://docs.rs/wrecked through https://crates.io/crates/wrecked.

Thank you mate :)
