### ISSUE TITLE
Getting an error with your example code

### ISSUE THREAD

**Issue by Joe23232** [quintinfsmith/wrecked#2]
Hi,

I am getting the following error based on your example code. This is my code inside `main.rs`:

```rust
use wrecked::{RectManager, RectColor};

fn main()
{
    let mut rectmanager = RectManager::new();
    let mut rect_id = rectmanager.new_rect(wrecked::TOP);

    rectmanager.resize(rect_id, 16, 5);

    rectmanager.set_string(rect_id, 2, 3, "Hello World!");

    rectmanager.draw();
}
```

And this is how I import your crate inside `cargo.toml` file:

```toml
[dependencies]
wrecked = "*"
```

And this is the error that I get:

```cmd
warning: unused import: `RectColor`
 --> src/main.rs:1:28
  |
1 | use wrecked::{RectManager, RectColor};
  |                            ^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0308]: mismatched types
 --> src/main.rs:8:24
  |
8 |     rectmanager.resize(rect_id, 16, 5);
  |                        ^^^^^^^ expected `usize`, found enum `std::result::Result`
  |
  = note: expected type `usize`
             found enum `std::result::Result<usize, RectError>`

error[E0308]: mismatched types
  --> src/main.rs:10:28
   |
10 |     rectmanager.set_string(rect_id, 2, 3, "Hello World!");
   |                            ^^^^^^^ expected `usize`, found enum `std::result::Result`
   |
   = note: expected type `usize`
              found enum `std::result::Result<usize, RectError>`

error: aborting due to 2 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0308`.
error: could not compile `firejail_plus`

To learn more, run the command again with --verbose.
```

I am not too sure why this is happening.

**Comment by quintinfsmith** [comment]
sorry about that, the docs are out of date because it's still really new.
```
rectmanager.new_rect(wrecked::TOP);
```
should be
```
let mut rect_id = rectmanager.new_rect(wrecked::TOP).ok().unwrap();
```
... Needed to make it handle potential errors in creating new rects.

**Comment by Joe23232** [comment]
> sorry about that, the docs are out of date because it's still really new.

All good mate 👍 

> ... Needed to make it handle potential errors in creating new rects.

Thanks for that.

While it works, I get this output:

```cmd
  Hello World!                                    
                                                  
                                                  
                                                  which should be handled
                                                  
                                                  
                                                  
                                                  s) in 0.32s
```

What is causing this line to output `which should be handled` and `s) in 0.32s` (the code I am using is the same except for the one line change as you suggested)?

**Comment by quintinfsmith** [comment]
That is the tail end of a couple lines of debug information from the cargo build. the entire screen isn't being cleared on initialization, which is definitely a bug. The code I've got checking the terminal size is a bit rickety at the moment. 
Can I ask what environment you're using to help me fix this issue?

**Comment by Joe23232** [comment]
> which is definitely a bug. The code I've got checking the terminal size is a bit rickety at the moment.

I understand mate :)

> Can I ask what environment you're using to help me fix this issue?

I am using vscode and I am using the built in terminal to run the code.

**Comment by quintinfsmith** [comment]
Issue fixed, version bumped.

**Comment by Joe23232** [comment]
THanks mate :)

**Comment by Joe23232** [comment]
How do I update it though whein the cargo file it is set to `wrecked = "*"`?

**Comment by quintinfsmith** [comment]
cargo update -p wrecked

**Comment by Joe23232** [comment]
THanks mate :)

**Comment by Joe23232** [comment]
I have another question then, something a bit wierd that is going on.

```rust
use wrecked::{RectManager, RectColor};

fn main()
{
    let mut rectmanager = RectManager::new();
    let mut rect_id = rectmanager.new_rect(wrecked::TOP).ok().unwrap();

    rectmanager.resize(rect_id, 16, 5);

    rectmanager.set_string(rect_id, 2, 3, "Hello World!");

    rectmanager.draw();
    //rectmanager.kill();
}
```

If the last line is commented out, the `"Hello World!"` is outputted but like the terminal behaves wierdly, for example if I scroll up and down I can see the previous commands I have ran and some other stuff (its a bit difficult to explain).

However if I uncomment out the last statement `rectmanager.kill();` I don't see anything on the screen (after kill the temrinal process and restart it on vscode).How come I don't see "Hello World" being printed and if the last line was commented how come the terminal behaves weird?

**Comment by quintinfsmith** [comment]
kill() returns the terminal to its original state, so when its commented out, the echo and cursor will be broken and the terminal will still be using the alternate screen buffer.
there doesn't appear to be anything keeping the code running in that function, so i imagine it's running, then immediately killing itself, so you just don't see anything on screen. use a timeout or wait for input to keep it alive long enough for you to see that it is rendering.

If the terminal isn't being returned to normal after its killed otherwise, then I imagine I haven't accounted for something about vscode code, and I'll check that out next chance I get.

**Comment by Joe23232** [comment]
> the echo and cursor will be broken and the terminal will still be using the alternate screen buffer.

Ah I see.

> there doesn't appear to be anything keeping the code running in that function, so i imagine it's running, then immediately killing itself, so you just don't see anything on screen.

Doesn't code run one at a time from top to bottom?

For example:

```rust

/*1.*/ rectmanager.set_string(rect_id, 2, 3, "Hello World!");

/*2.*/ rectmanager.draw();
/*3.*/ rectmanager.kill();
```

So wouldn't line 2 have to finish doing its thing before it can run line 3? Line 2 I believe draws the `"Hello World!"` onto the screen, right?

> If the terminal isn't being returned to normal after its killed otherwise, then I imagine I haven't accounted for something about vscode code, and I'll check that out next chance I get.

It is returned to its original state _after_ the rect has been killed.

**Comment by quintinfsmith** [comment]
yes it does but kill() tears down everything that gets written to the terminal while the code was running. So 'Hello World!' is showing up, but only for an instant. so you just can't see it. if you add a timeout between draw() and kill(), you'll see what i mean.

**Comment by Joe23232** [comment]
I see now, now it makes sense :)

Is timeout part of your crate or is there some other crate I have to import?

**Comment by quintinfsmith** [comment]
No sorry, years of javascript has just tainted my vocabulary, i meant a delay. (ie thread::sleep)
I never intended to have an interactive part of this library, so i don't have anything included to keep it alive. 
My thought was that it would remain alive as long as whatever program was using it was running.

**Comment by Joe23232** [comment]
> No sorry, years of javascript has just tainted my vocabulary, i meant a delay. (ie time::sleep)

All good and thanks mate :)

> I never intended to have an interactive part of this library.

So that means it can't take keyboard entries and register mouse clicks (i.e. on a button)?

> My thought was that it would remain alive as long as whatever program was using it was running.

Of course makes sense I want something like this unless if the user wants to end the program.

**Comment by quintinfsmith** [comment]
> So that means it can't take keyboard entries and register mouse clicks (i.e. on a button)?

you'll need to write your own input handler or use a crate that does that. 
I may have never intended to include this behavior, but I'm suddenly starkly aware that anyone using this would need to at least have non-canonical keyboard input. So I'll think about prioritizing it.

**Comment by Joe23232** [comment]
I see, thanks mate :)
